import { db } from "../server/db";
import { jobs } from "@shared/schema";

const southAfricanJobs = [
  // Tech & IT Jobs
  {
    title: "Senior Full Stack Developer",
    company: "Takealot",
    salary: "R650,000 - R850,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Technology",
    description: "Join South Africa's leading e-commerce platform. Build scalable solutions using React, Node.js, and AWS. Work on systems that serve millions of customers daily. Require 5+ years experience with modern web technologies.",
    skills: ["React", "Node.js", "TypeScript", "AWS", "PostgreSQL", "Docker"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Software Engineer (Graduate)",
    company: "Nedbank",
    salary: "R350,000 - R450,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Graduate programme for software engineers. Learn banking systems, work with experienced developers, and contribute to digital transformation initiatives. Java, Spring Boot, and microservices experience preferred.",
    skills: ["Java", "Spring Boot", "SQL", "Git", "REST APIs"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Data Scientist",
    company: "Discovery",
    salary: "R700,000 - R950,000 per annum",
    location: "Sandton, Gauteng",
    sector: "Insurance & Healthcare",
    description: "Build ML models to improve health outcomes. Work with massive datasets, develop predictive algorithms, and drive data-driven decision making. Python, TensorFlow, and statistical modeling expertise required.",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "Statistics", "R"],
    nqfLevel: 8,
    workType: "hybrid",
  },
  {
    title: "DevOps Engineer",
    company: "Mr Price Group",
    salary: "R550,000 - R750,000 per annum",
    location: "Durban, KwaZulu-Natal",
    sector: "Retail",
    description: "Manage cloud infrastructure, CI/CD pipelines, and deployment automation. Work with Docker, Kubernetes, and Azure. Support retail systems serving 1000+ stores nationwide.",
    skills: ["Docker", "Kubernetes", "Azure", "Terraform", "Jenkins", "Linux"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Mobile Developer (iOS & Android)",
    company: "FNB",
    salary: "R600,000 - R800,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Develop and maintain FNB's mobile banking apps. Work with Swift, Kotlin, and React Native. Ensure secure, scalable solutions for millions of banking customers.",
    skills: ["Swift", "Kotlin", "React Native", "Firebase", "REST APIs"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Cybersecurity Analyst",
    company: "Standard Bank",
    salary: "R500,000 - R700,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Protect banking systems from cyber threats. Monitor security events, conduct penetration testing, and ensure compliance with banking regulations. CISSP or CEH certification preferred.",
    skills: ["Network Security", "Penetration Testing", "SIEM", "Firewall", "Compliance"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Cloud Architect",
    company: "Vodacom",
    salary: "R800,000 - R1,200,000 per annum",
    location: "Midrand, Gauteng",
    sector: "Telecommunications",
    description: "Design and implement cloud solutions for Africa's leading telco. Work with AWS, Azure, and GCP. Lead cloud migration projects and architect scalable infrastructure.",
    skills: ["AWS", "Azure", "GCP", "Microservices", "Terraform", "Kubernetes"],
    nqfLevel: 8,
    workType: "hybrid",
  },
  {
    title: "Frontend Developer",
    company: "Luno",
    salary: "R550,000 - R750,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Fintech",
    description: "Build beautiful, responsive UIs for cryptocurrency trading platform. Work with React, TypeScript, and modern frontend tools. Join a fast-growing fintech serving millions across Africa.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    nqfLevel: 6,
    workType: "remote",
  },
  {
    title: "Backend Developer (Python)",
    company: "Yoco",
    salary: "R600,000 - R850,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Fintech",
    description: "Build payment processing systems for small businesses. Python, Django, and microservices experience essential. Work on high-volume transactional systems with 99.9% uptime requirements.",
    skills: ["Python", "Django", "PostgreSQL", "Redis", "Docker", "Microservices"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "UI/UX Designer",
    company: "Capitec Bank",
    salary: "R450,000 - R650,000 per annum",
    location: "Stellenbosch, Western Cape",
    sector: "Banking & Finance",
    description: "Design intuitive banking experiences for South Africa's fastest-growing bank. Create user-centered designs, conduct usability testing, and collaborate with developers. Figma and design systems experience required.",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems"],
    nqfLevel: 6,
    workType: "hybrid",
  },

  // Business & Management
  {
    title: "Project Manager (IT)",
    company: "Shoprite Checkers",
    salary: "R550,000 - R750,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Retail",
    description: "Manage IT projects for Africa's largest retailer. Lead cross-functional teams, ensure timely delivery, and drive digital transformation. PMP certification preferred.",
    skills: ["Project Management", "Agile", "Scrum", "Stakeholder Management", "Budget Control"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Business Analyst",
    company: "Old Mutual",
    salary: "R450,000 - R600,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Insurance & Finance",
    description: "Analyze business processes, gather requirements, and support digital initiatives. Work with stakeholders to improve operational efficiency. Financial services experience advantageous.",
    skills: ["Business Analysis", "SQL", "Data Analysis", "Requirements Gathering", "Process Mapping"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Product Manager",
    company: "TymeBank",
    salary: "R700,000 - R950,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Own digital banking products from conception to launch. Define product roadmap, prioritize features, and work with engineering teams. Experience in fintech or digital products essential.",
    skills: ["Product Strategy", "Roadmap Planning", "Agile", "User Stories", "Analytics"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Scrum Master",
    company: "Absa",
    salary: "R500,000 - R700,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Facilitate agile ceremonies, remove blockers, and coach teams in agile practices. Work with multiple squads to deliver banking solutions. CSM certification required.",
    skills: ["Scrum", "Agile Coaching", "Jira", "Facilitation", "Conflict Resolution"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Digital Marketing Manager",
    company: "Woolworths",
    salary: "R500,000 - R700,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Retail",
    description: "Lead digital marketing strategy for premium retail brand. Manage campaigns across social media, email, and web. Drive online sales growth and brand engagement.",
    skills: ["Digital Marketing", "SEO", "Google Analytics", "Social Media", "Email Marketing"],
    nqfLevel: 6,
    workType: "hybrid",
  },

  // Engineering & Operations
  {
    title: "Electrical Engineer",
    company: "Eskom",
    salary: "R450,000 - R650,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Energy & Utilities",
    description: "Design and maintain electrical distribution systems. Work on power generation and transmission projects. Electrical engineering degree and registration with ECSA required.",
    skills: ["Electrical Design", "AutoCAD", "Power Systems", "Project Engineering", "ECSA Registration"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Mechanical Engineer",
    company: "Sasol",
    salary: "R500,000 - R750,000 per annum",
    location: "Secunda, Mpumalanga",
    sector: "Energy & Chemicals",
    description: "Support chemical plant operations and maintenance. Design process improvements, troubleshoot equipment, and ensure safety compliance. Mining or petrochemical experience preferred.",
    skills: ["Mechanical Engineering", "CAD", "Process Design", "Maintenance", "Safety Management"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Civil Engineer",
    company: "SANRAL",
    salary: "R400,000 - R600,000 per annum",
    location: "Pretoria, Gauteng",
    sector: "Construction & Infrastructure",
    description: "Design and oversee road infrastructure projects. Conduct site inspections, manage contractors, and ensure quality standards. Professional registration advantageous.",
    skills: ["Civil Engineering", "Project Management", "AutoCAD", "Site Management", "Quality Control"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Supply Chain Manager",
    company: "Massmart",
    salary: "R550,000 - R800,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Retail",
    description: "Optimize supply chain operations for Walmart-owned retailer. Manage logistics, inventory, and vendor relationships. Drive cost savings and operational efficiency.",
    skills: ["Supply Chain", "Logistics", "Inventory Management", "Vendor Management", "SAP"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Quality Assurance Engineer",
    company: "BMW South Africa",
    salary: "R400,000 - R550,000 per annum",
    location: "Rosslyn, Gauteng",
    sector: "Manufacturing",
    description: "Ensure vehicle quality standards in manufacturing. Conduct inspections, implement quality systems, and drive continuous improvement. Automotive experience essential.",
    skills: ["Quality Management", "Six Sigma", "ISO Standards", "Root Cause Analysis", "Manufacturing"],
    nqfLevel: 6,
    workType: "onsite",
  },

  // Healthcare & Science
  {
    title: "Registered Nurse (ICU)",
    company: "Netcare",
    salary: "R350,000 - R500,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Healthcare",
    description: "Provide critical care nursing in private hospital ICU. Manage ventilated patients, administer medications, and work in multidisciplinary teams. SANC registration and ICU experience required.",
    skills: ["Critical Care", "Patient Monitoring", "ICU Protocols", "SANC Registration", "Emergency Response"],
    nqfLevel: 6,
    workType: "onsite",
  },
  {
    title: "Pharmacist",
    company: "Clicks Group",
    salary: "R400,000 - R550,000 per annum",
    location: "Durban, KwaZulu-Natal",
    sector: "Healthcare & Retail",
    description: "Dispense medications and provide pharmaceutical care in retail pharmacy. Counsel patients, manage stock, and ensure regulatory compliance. SAPC registration essential.",
    skills: ["Pharmaceutical Care", "Dispensing", "Patient Counseling", "Inventory", "SAPC Registration"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Clinical Research Coordinator",
    company: "Wits University",
    salary: "R300,000 - R450,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Research & Academia",
    description: "Coordinate clinical trials and research studies. Manage participant recruitment, data collection, and ethical compliance. Experience with GCP and REDCap preferred.",
    skills: ["Clinical Research", "GCP", "Data Management", "Ethics", "Patient Recruitment"],
    nqfLevel: 7,
    workType: "onsite",
  },
  {
    title: "Data Analyst (Healthcare)",
    company: "Discovery Health",
    salary: "R400,000 - R600,000 per annum",
    location: "Sandton, Gauteng",
    sector: "Insurance & Healthcare",
    description: "Analyze healthcare claims data to identify trends and improve member outcomes. Build dashboards, create reports, and support actuarial teams. SQL and Power BI expertise required.",
    skills: ["SQL", "Power BI", "Python", "Healthcare Analytics", "Data Visualization"],
    nqfLevel: 6,
    workType: "hybrid",
  },

  // Finance & Accounting
  {
    title: "Financial Analyst",
    company: "PwC South Africa",
    salary: "R350,000 - R500,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Professional Services",
    description: "Provide financial analysis and advisory services to clients. Build financial models, conduct valuations, and support M&A transactions. CA(SA) or CFA progress preferred.",
    skills: ["Financial Modeling", "Excel", "Valuation", "Financial Reporting", "Advisory"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Chartered Accountant (Audit)",
    company: "Deloitte",
    salary: "R450,000 - R650,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Professional Services",
    description: "Conduct financial audits for corporate clients. Review financial statements, assess controls, and ensure compliance. CA(SA) qualification and articles completed required.",
    skills: ["Audit", "Financial Statements", "IFRS", "Risk Assessment", "CA(SA)"],
    nqfLevel: 8,
    workType: "hybrid",
  },
  {
    title: "Tax Consultant",
    company: "KPMG",
    salary: "R400,000 - R600,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Professional Services",
    description: "Provide tax advisory services to corporate clients. Handle tax compliance, planning, and dispute resolution. Tax qualification (SAIT/CA) and experience with SARS essential.",
    skills: ["Tax Compliance", "Tax Planning", "SARS", "Corporate Tax", "Advisory"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Investment Analyst",
    company: "Allan Gray",
    salary: "R500,000 - R750,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Asset Management",
    description: "Analyze investment opportunities across equity and fixed income. Conduct research, build models, and support portfolio management decisions. CFA charter holder preferred.",
    skills: ["Investment Analysis", "Financial Modeling", "Equity Research", "CFA", "Valuation"],
    nqfLevel: 8,
    workType: "onsite",
  },
  {
    title: "Credit Risk Analyst",
    company: "RMB (Rand Merchant Bank)",
    salary: "R450,000 - R650,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Banking & Finance",
    description: "Assess credit risk for corporate lending. Analyze financial statements, assign risk ratings, and monitor loan portfolios. Banking and credit experience essential.",
    skills: ["Credit Analysis", "Risk Assessment", "Financial Analysis", "Banking", "Excel"],
    nqfLevel: 7,
    workType: "hybrid",
  },

  // Sales & Customer Service
  {
    title: "Sales Executive (B2B)",
    company: "Microsoft South Africa",
    salary: "R400,000 - R700,000 per annum (OTE)",
    location: "Johannesburg, Gauteng",
    sector: "Technology",
    description: "Sell Microsoft cloud solutions to enterprise clients. Build relationships, drive revenue growth, and exceed sales targets. Experience with Azure and M365 preferred.",
    skills: ["B2B Sales", "Cloud Solutions", "Relationship Building", "Negotiation", "Sales Strategy"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Customer Success Manager",
    company: "SweepSouth",
    salary: "R350,000 - R500,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Technology & Services",
    description: "Ensure customer satisfaction and retention for on-demand services platform. Manage accounts, resolve issues, and drive product adoption. Tech startup experience beneficial.",
    skills: ["Customer Success", "Account Management", "CRM", "Problem Solving", "Communication"],
    nqfLevel: 6,
    workType: "remote",
  },
  {
    title: "Business Development Manager",
    company: "MTN Group",
    salary: "R550,000 - R800,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Telecommunications",
    description: "Identify and pursue new business opportunities across Africa. Develop partnerships, negotiate contracts, and drive revenue growth. Telecom experience advantageous.",
    skills: ["Business Development", "Partnership Management", "Contract Negotiation", "Strategy", "Telecom"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Contact Centre Agent",
    company: "Telkom",
    salary: "R180,000 - R250,000 per annum",
    location: "Pretoria, Gauteng",
    sector: "Telecommunications",
    description: "Handle customer queries via phone and digital channels. Resolve technical issues, process orders, and ensure customer satisfaction. Matric and customer service experience required.",
    skills: ["Customer Service", "Communication", "Problem Solving", "CRM Systems", "Call Handling"],
    nqfLevel: 4,
    workType: "onsite",
  },

  // Education & Training
  {
    title: "Learning & Development Specialist",
    company: "Liberty Group",
    salary: "R400,000 - R550,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Insurance & Finance",
    description: "Design and deliver employee training programs. Develop e-learning content, facilitate workshops, and measure training effectiveness. L&D or HR qualification preferred.",
    skills: ["Training Design", "Facilitation", "E-Learning", "Needs Analysis", "Learning Management"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Mathematics Teacher (High School)",
    company: "Western Cape Education Department",
    salary: "R280,000 - R400,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Education",
    description: "Teach mathematics to Grade 10-12 learners. Prepare students for NSC exams, develop lesson plans, and assess progress. SACE registration and teaching qualification required.",
    skills: ["Mathematics", "Teaching", "Lesson Planning", "Assessment", "SACE Registration"],
    nqfLevel: 6,
    workType: "onsite",
  },
  {
    title: "Corporate Trainer (IT Skills)",
    company: "EOH",
    salary: "R350,000 - R500,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Technology & Training",
    description: "Deliver technical training on IT systems and software. Conduct workshops, create training materials, and assess learner competency. Microsoft certifications preferred.",
    skills: ["Technical Training", "Microsoft Office", "Cloud Computing", "Presentation", "Curriculum Development"],
    nqfLevel: 6,
    workType: "hybrid",
  },

  // Legal & Compliance
  {
    title: "Legal Advisor",
    company: "Sanlam",
    salary: "R500,000 - R750,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Insurance & Finance",
    description: "Provide legal advice on commercial contracts, compliance, and regulatory matters. Draft agreements, manage disputes, and support business units. LLB and admitted attorney required.",
    skills: ["Commercial Law", "Contract Drafting", "Compliance", "Legal Advisory", "Admitted Attorney"],
    nqfLevel: 8,
    workType: "hybrid",
  },
  {
    title: "Compliance Officer",
    company: "Investec",
    salary: "R450,000 - R650,000 per annum",
    location: "Sandton, Gauteng",
    sector: "Banking & Finance",
    description: "Ensure compliance with financial regulations (FICA, FIC Act, FAIS). Conduct compliance reviews, monitor controls, and report to regulators. Banking compliance experience essential.",
    skills: ["Compliance", "FICA", "FAIS", "Risk Management", "Regulatory Reporting"],
    nqfLevel: 7,
    workType: "hybrid",
  },

  // HR & Recruitment
  {
    title: "HR Business Partner",
    company: "Sasol",
    salary: "R500,000 - R700,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Energy & Chemicals",
    description: "Partner with business leaders on HR strategy. Manage talent, employee relations, and organizational development. HR qualification and HRBP experience required.",
    skills: ["HR Strategy", "Talent Management", "Employee Relations", "Organizational Development", "Labour Law"],
    nqfLevel: 7,
    workType: "hybrid",
  },
  {
    title: "Talent Acquisition Specialist",
    company: "Amazon Web Services (AWS)",
    salary: "R450,000 - R650,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Technology",
    description: "Recruit top tech talent for AWS in Africa. Manage end-to-end recruitment, build talent pipelines, and partner with hiring managers. Tech recruitment experience preferred.",
    skills: ["Recruitment", "Tech Hiring", "ATS", "Interviewing", "Talent Sourcing"],
    nqfLevel: 6,
    workType: "remote",
  },
  {
    title: "Payroll Administrator",
    company: "Clicks Group",
    salary: "R250,000 - R350,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Retail",
    description: "Process monthly payroll for 10,000+ employees. Ensure accuracy, compliance with tax laws, and timely payments. Payroll certification and VIP/Sage experience required.",
    skills: ["Payroll Processing", "VIP Payroll", "Tax Compliance", "SARS EMP201", "Attention to Detail"],
    nqfLevel: 5,
    workType: "onsite",
  },

  // Hospitality & Tourism
  {
    title: "Hotel Manager",
    company: "Sun International",
    salary: "R400,000 - R600,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Hospitality",
    description: "Manage hotel operations including front desk, housekeeping, and guest services. Ensure exceptional guest experiences, manage budgets, and lead teams. Hotel management qualification preferred.",
    skills: ["Hotel Management", "Guest Services", "Budget Management", "Team Leadership", "Operations"],
    nqfLevel: 6,
    workType: "onsite",
  },
  {
    title: "Chef de Partie",
    company: "The Saxon Hotel",
    salary: "R220,000 - R320,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Hospitality",
    description: "Prepare high-end cuisine in 5-star hotel kitchen. Manage section, train junior chefs, and maintain quality standards. Culinary qualification and fine dining experience required.",
    skills: ["Culinary Arts", "Fine Dining", "Kitchen Management", "Food Safety", "Menu Planning"],
    nqfLevel: 5,
    workType: "onsite",
  },
  {
    title: "Travel Consultant",
    company: "Flight Centre",
    salary: "R200,000 - R350,000 per annum (base + commission)",
    location: "Sandton, Gauteng",
    sector: "Travel & Tourism",
    description: "Design travel packages, book flights and accommodation, and provide exceptional customer service. Amadeus experience and destination knowledge essential.",
    skills: ["Travel Sales", "Amadeus", "Customer Service", "Destination Knowledge", "Sales"],
    nqfLevel: 5,
    workType: "onsite",
  },

  // Logistics & Transport
  {
    title: "Logistics Coordinator",
    company: "Imperial Logistics",
    salary: "R280,000 - R400,000 per annum",
    location: "Johannesburg, Gauteng",
    sector: "Logistics",
    description: "Coordinate freight movements, manage transport schedules, and liaise with customers. Optimize routes, track shipments, and resolve logistics issues. Transport planning experience required.",
    skills: ["Logistics Coordination", "Transport Planning", "Customer Service", "Problem Solving", "Excel"],
    nqfLevel: 5,
    workType: "onsite",
  },
  {
    title: "Warehouse Manager",
    company: "Bidvest",
    salary: "R350,000 - R500,000 per annum",
    location: "Durban, KwaZulu-Natal",
    sector: "Logistics",
    description: "Manage warehouse operations including receiving, storage, and dispatch. Ensure inventory accuracy, implement safety standards, and optimize processes. WMS experience essential.",
    skills: ["Warehouse Management", "Inventory Control", "WMS", "Team Management", "Safety Compliance"],
    nqfLevel: 6,
    workType: "onsite",
  },

  // Media & Creative
  {
    title: "Graphic Designer",
    company: "Ogilvy South Africa",
    salary: "R280,000 - R450,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Marketing & Advertising",
    description: "Create visual content for advertising campaigns. Design for print and digital, collaborate with creative teams, and work on major brand campaigns. Portfolio required.",
    skills: ["Graphic Design", "Adobe Creative Suite", "Branding", "Typography", "Creative Thinking"],
    nqfLevel: 6,
    workType: "hybrid",
  },
  {
    title: "Content Writer",
    company: "Prezly",
    salary: "R250,000 - R400,000 per annum",
    location: "Remote (South Africa)",
    sector: "Technology & Media",
    description: "Write compelling content for SaaS platform. Create blog posts, case studies, and marketing copy. Tech writing experience and SEO knowledge beneficial.",
    skills: ["Content Writing", "SEO", "Copywriting", "Research", "Editing"],
    nqfLevel: 5,
    workType: "remote",
  },
  {
    title: "Social Media Manager",
    company: "Pick n Pay",
    salary: "R320,000 - R480,000 per annum",
    location: "Cape Town, Western Cape",
    sector: "Retail",
    description: "Manage social media presence across all platforms. Create content calendars, engage with customers, and grow online community. Experience with Meta Business Suite required.",
    skills: ["Social Media", "Content Creation", "Community Management", "Analytics", "Brand Management"],
    nqfLevel: 6,
    workType: "hybrid",
  },
];

async function seedJobs() {
  try {
    console.log("Starting to seed jobs...");
    
    const result = await db.insert(jobs).values(southAfricanJobs).returning();
    
    console.log(`✅ Successfully seeded ${result.length} South African jobs!`);
    console.log("\nJob breakdown by sector:");
    
    const sectors = southAfricanJobs.reduce((acc, job) => {
      acc[job.sector] = (acc[job.sector] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    Object.entries(sectors).forEach(([sector, count]) => {
      console.log(`  ${sector}: ${count} jobs`);
    });
    
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding jobs:", error);
    process.exit(1);
  }
}

seedJobs();
